server:
  port: 80

spring:
  h2:
    console:
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:hello-jpa;
    username: abc
    password: abc
  jpa:
    open-in-view: true
    properties:
      hibernate:
        show-sql: true
        format_sql: true
